theme: jekyll-theme-minimal
logo: /GrabShot/Assets.xcassets/AppIcon256.imageset/256x256%402x.png
show_downloads: false
appstore: /images/badge-download-on-the-mac-app-store.svg
donate: /images/badge-donate.svg
